mParticle/mparticle-web-sdk

README.md
package.json
test/runner.js

Leverages browser-sync to run mocha tests in browser w/ auto-refreshing on file changes. Includes relevant updates to README.

Add test npm command w/ browser-sync

---

src/identity.js
test/src/tests-identity.js

In some scenarios, it might be necessary to define the alias scope to something other than the default "device" option. This is not allowed on the web SDK at the moment, even though it is on the Identity API.
- Unit tested
- Tested on a local application that uses the SDK, with and without the scope param
I didn't change the `convertAliasToNative` method as I'm not aware if the native clients support this param.
- What else needs change? Docs, TypeScript types, etc.
- Can someone review the TS type definitions? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54813

feat: Allow scope param on user alias requests

---

.github/workflows/release.yml

Update semantic release Node version from 12.x to 16.x

ci: update semantic release Node version to 16.x

---

.github/workflows/release.yml

This release.yml file is not running due to an indentation error.  Also updating `confirm-master-branch` --> `confirm-public-repo-master-branch` as the job name was updated but the `needs` that depends on the job didn't update its name.

ci: update indentation and job name in release.yml

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

In some cases, we may have an npm error log that gets clobbered by Github Actions stdout. Github actions writes these to its file system but they can't be picked up by the UI. Archiving these logs as an artifact will allow us to pick them up.
This was tested as during sample apps development.
Closes https://go.mparticle.com/work/SQDSDKS-3626

ci: add archive npm logs task to workflow

---

package-lock.json
package.json
src/sdkRuntimeModels.ts
src/sdkToEventsApiConverter.ts
src/serverModel.js
src/store.js
test/src/tests-core-sdk.js

Add Support for Bundle ID to Web SDK so that we can track Sample App or host app usage independent of workspace.
The expectation is that a user can pass in a `packageName` similar to our Native SDK and this will attach a `package` attribute to the `application_info` which can later be filtered along with `os` to determine app usage across three core platforms (Web, iOS and Android).
Manually test that web SDK continues to work with or without this new config attribute and run automated tests.
Closes https://go.mparticle.com/work/SQDSDKS-3728

feat: add package to batch application info

---

.github/workflows/release.yml

- Change order of release steps so that tests run before release branch is created
- No steps should run until tests and confirmations run

ci: Update order of release steps

---

package.json

Add NPM Scripts that will allow us to compress the js bundle and report file size to be used in a later github action
N/A
Closes https://go.mparticle.com/work/SQDSDKS-4316

ci: Add NPM Scripts to compress and log bundle size

---

src/apiClient.js
test/src/tests-main.js
test/src/tests-temp-session-bug-fix.js

Context - I originally found this bug in [PR#313](https://github.com/mParticle/mparticle-web-sdk/pull/313), and included the fix in that PR.  PR#313 is on hold right now. I am cherry picking the commit from PR#313 so that we can fix the bug and not have a larger PR block it.
Summary - For the batching endpoint, we were not updating the last event sent timestamp, or `LES`.  This may result in lower than actual session lengths under certain circumstances. If a user remains on the page when a session ends, there is no issue.  If a user returns to a page beyond the session timeout, then there is also no issue. The edge case that this affects is if a user spends less than the session timeout on the page, then returns to the page shortly thereafter. We will check cookies to see the last event …

fix: Update last event sent timestamp for batch uploads

---

dist/mparticle.js
src/identity.js
test/src/tests-identities-attributes.js

A client reported that UAC events are forwarded on initialization everytime for some attributes even though the values are not changed. Per investigating it seemed that values that are set to false are only affected by this issue, furthermore I was able to also confirm that values such as 0 and an empty string '' would have the same issue since Javascript recognize them as null values. The code change here is to only change previousUserAttributeValue when it comes in as undefined since this is the value when it is not seen before.
Tested locally with overrides in sample app and also added unit testing case

fix: Sending multiple UAC events for same value UA

---

src/helpers.js
src/utils.ts
src/validators.ts
test/src/tests-utils.ts

- Move `parseStringOrNumber` into Utils for better organization of utility functions
Closes https://go.mparticle.com/work/SQDSDKS-4656

refactor: Move parseStringOrNumber into Utils

---

src/apiClient.js
src/mp-instance.js
test/src/tests-forwarders.js

There are cases (GA4 and Adobe) when a customer checks `forward web requests server side`, but the server needs additional information from the client to forward information properly. In the case of GA4, they need a `client_id`, and you can only get this client side from the GA4 SDKs.  We classify `client_id` as an `integration attribute` or `ia`.
([GA4 server side web kit](https://github.com/mparticle-integrations/mparticle-javascript-integration-google-analytics-4/blob/master/packages/GA4Server/src/GoogleAnalytics4EventForwarderServerSide.js) for example) is a simplified kit whose sole purpose is to grab the `client_id` and set it as an `ia` on a payload so that the server has all the required information before forwarding events.
The steps are:
1. [kit tells core SDK to delay sending …

fix: Process queued events after there are no more integration delays

---

src/mp-instance.js
src/mparticle-instance-manager.js
src/stub/mparticle.stub.js
src/types.js
test/src/tests-core-sdk.js
test/src/tests-types.js
test/stub/tests-mParticle-stub.js

- expose `getEnvironment()` function to mParticle Instance which will return the current environment setting in `Store`
Closes https://go.mparticle.com/work/SQDSDKS-4725

feat: Expose getEnvironment() for mParticle Instance

---

src/batchUploader.ts
src/utils.ts
test/src/tests-batchUploader.ts
test/src/tests-utils.ts

- Within `BatchUploader.queueEvent`, we are only checking if the event is `null`, but not if it is actually empty.
- We don't have reliable test data directly related to this bug report, and is unlikely that an event can get to this point in the code while being empty, but we should be more defensive, just in case.
- Using the browser debugger, manually send events into the batch uploader and verify that batches without events are not created.
Closes https://go.mparticle.com/work/SQDSDKS-4737

fix: Prevent Batches from queuing empty events

---

.github/workflows/pull-request.yml
.github/workflows/reusable-workflows.yml

Ever since the security check was added to the Github action, it prevented the build and test from running.  This should fix that.  Example failure here - https://github.com/mParticle/mparticle-web-sdk/actions/runs/3789930377
NA

ci: Fix security lint checks

---

src/mockBatchCreator.ts
src/mp-instance.js
src/mparticle-instance-manager.js
src/store.ts
test/src/tests-core-sdk.js

Add ability for wrapper SDKs to set their name and version on the core SDK.
Added unit tests and confirmed locally
Closes https://go.mparticle.com/work/SQDSDKS-4758
[SQDSDKS-4758]: https://mparticle-eng.atlassian.net/browse/SQDSDKS-4758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Add wrapper SDK name/version setter for diagnostics

---

src/configAPIClient.ts
src/sdkRuntimeModels.ts
src/store.ts
test/src/tests-config-api-client.ts
test/src/tests-main.js

- Migrate ConfigAPIClient to TypeScript
- Add Unit Tests
- Test manually via Sample App
- Closes https://go.mparticle.com/work/SQDSDKS-5010

refactor: Migrate Config API Client to TypeScript

---

src/sdkToEventsApiConverter.ts

- In cases where the event is missing a consent state, we should use the current user's consent state
- Closes https://go.mparticle.com/work/SQDSDKS-5047
- Broken out of #383 to split out unrelated functionality in that feature branch

fix: use currentUser consent state as backup if missing in last event

---

src/batchUploader.ts
test/src/tests-batchUploader.ts
test/src/tests-beaconUpload.ts
test/src/tests-main.js

This pull request refactors parts of the BatchUploader to better handle asynchronous uploads. Currently, a single asynchronous request is made that iterates through a list of batches, yet each batch is individually uploaded to the server. Loops inside of promises are not recommended in JavaScript as they could lead a longer turnaround time to process the response or other unexpected results. By breaking up the single upload promise into individual …

refactor: Modify BatchUploader to use promises for individual uploads

---

src/vault.ts
test/src/tests-main.js
test/src/tests-vault.ts

- Create a Wrapper Class around Local Storage
- Wrapper should allow batches to be saved and retrieved from local storage
- Wrapper should allow batches to be purged without affecting other local storage items
- This wrapper will be part of a larger initiative to refactor persistence
- Closes https://go.mparticle.com/work/SQDSDKS-4714
- Reintroduces approved changes …

feat: Add Persistence Wrapper

---

src/forwarders.js
src/helpers.js
src/identity.js
test/src/tests-forwarders.js
test/src/utils.js

- User attributes when removes are not respecting the filters set which leads some forwarder to set them as null even though they're filtered. The fix here is to not fire removeUserAttribute for a filtered UA.
- Was tested locally via local overrides and passed unit testing
- Closes https://mparticle-eng.atlassian.net/browse/PRODRDMP-5414

fix: removeUserAttribute and forwarder filters fix

---

.github/workflows/dependabot-branch-rebase.yml

- Set up job to inherit token
- N/A - Github Actions cannot be tested locally
- Closes https://go.mparticle.com/work/SQDSDKS-5203

ci: add in missing inherit in rebase job

---

.github/workflows/pull-request.yml

I noticed that with the new CI steps merged from this [PR](https://go.mparticle.com/work/SQDSDKS-5163) that tests for commonjs and modulejs were failing in GHA, even though they were passing locally. 
https://github.com/mParticle/mparticle-web-sdk/actions/runs/4416514762/jobs/7741341885 
https://github.com/mParticle/mparticle-web-sdk/actions/runs/4416514762/jobs/7741341109 
Upon additional testing, it seems that there is an issue with downloading from …

ci: Manually build at each job instead of downloading the archive

---

src/forwarders.js
src/mockBatchCreator.ts
src/mp-instance.js
src/sdkRuntimeModels.ts
src/store.ts
test/src/tests-forwarders.js
test/src/tests-store.ts
test/src/tests-temp-session-bug-fix.js
test/src/utils.js

This PR introduces an API change in order to support sideloaded kits.  This is supported on both NPM and CDN.  When the customer imports a custom kit and uses the following CDN:
```
mParticle.config.sideloadedKits = [SideloadedKit];
```
The sideloaded kit is processed and added to activeForwarders array so that all mParticle methods (ie. logPageView, logEvent, login, etc) will map to it. 
Note that as this is the first milestone, there is no filtering …

feat: Support sideloaded kits

---

.github/dependabot.yml

- Allow dependabot to only update direct dependencies
- - Add new dependencies label

ci: Allow dependabot to only update direct dependencies; add new dependencies label

---

src/apiClient.ts
src/helpers.js
src/sdkRuntimeModels.ts
src/utils.ts
test/src/tests-helpers.js
test/src/tests-utils.ts

- Moved out `getRampNumber` along with associated methods, `generateHash`, `generateRandomValue`, and `generateUniqueId`, into Utils modules so that we can decouple utility functions from Helper. Helper has a hard dependency on the full SDK instance and these are simple utility functions that do not require such tight coupling.
- Add tests where necessary for added coverage.
- Verify that ramp number is generated
- Verify that randomized guids are …

refactor: Move getRampNumber and random number generators into utils

---

.github/workflows/release.yml

We should update all web sdk workflows to use `ubuntu-latest` because ubuntu-18.04 is deprecated and preventing releases from happening.
- Closes https://go.mparticle.com/work/SQDSDKS-5295

ci: Update workflows to ubuntu-latest

---

src/batchUploader.ts
src/constants.ts
src/mockBatchCreator.ts
src/store.ts
src/vault.ts
test/karma.config.js
test/src/tests-batchUploader.ts
test/src/tests-vault.ts

* Introduces a refactor of our Web API Storage Wrapper (Vault) to support SessionStorage and LocalStorage
* Implements two instances of Vaults; one for Events (Session Storage), and a second for Batches (Local Storage)
* As events are queued, they are placed into Session Storage for later processing. Once the `prepareAndUpload` method is triggered, events are removed from Session Storage and converted to Batches for upload.
* If any Batches exist in …

feat: Add Offline Storage for Events and Batches via Feature Flag

---

src/apiClient.ts
src/constants.ts
src/identity.js
src/mp-instance.js
src/store.ts
test/integrations/requirejs/karma.requirejs.config.js
test/integrations/requirejs/test-requirejs.js
test/src/config.ts
test/src/tests-apiClient.ts
test/src/tests-batchUploader.ts
test/src/tests-consent.ts
test/src/tests-cookie-syncing.js
test/src/tests-core-sdk.js
test/src/tests-eCommerce.js
test/src/tests-event-logging.js
test/src/tests-forwarders.js
test/src/tests-identities-attributes.js
test/src/tests-identity.js
test/src/tests-kit-blocking.ts
test/src/tests-mParticleUser.js
test/src/tests-main.js
test/src/tests-migrations.js
test/src/tests-mparticle-instance-manager.js
test/src/tests-persistence.js
test/src/tests-queue-public-methods.js
test/src/tests-self-hosting-specific.js
test/src/tests-serverModel.ts
test/src/tests-store.ts
test/src/tests-temp-session-bug-fix.js
test/src/utils.js

In this PR, we are removing the V2 events code path, as this is no longer used by any customers.  All customers are on the V3 endpoint.  The majority of these line changes are tests because most tests were expecting the V2 code path to be used.   This is a re-do of [and old PR](https://github.com/mParticle/mparticle-web-sdk/pull/313) which was approved in the past, but was never released.  
Tests run locally
- Closes …

fix: Remove non-batching event code path (v2 events endpoint)

---

test/src/tests-cookie-syncing.js

Current cookie sync URL is using an imgur pixel, and imgur recently updated TOS and our cookie sync tests are breaking.  This fixes the issue.
- Closes https://go.mparticle.com/work/SQDSDKS-5372

 test: Change url of pixel for cookie sync

---

src/configAPIClient.ts
src/sideloadedKit.ts
src/types.interfaces.ts
test/jest/sideloadedKit.spec.ts

This PR creates the `MPSideloadedKit` class. This takes an unregistered kitInstance and provides public methods that allow a developer to add hash values for filters of event names/attributes/etc to filter out certain data points from being sent to the specified kit.
- Closes https://go.mparticle.com/work/SQDSDKS-5350

feat: Add MPSideloadedKit class

---

src/mockBatchCreator.ts
src/persistence.js
src/sdkRuntimeModels.ts
test/src/tests-persistence.ts

- Change order of priority for device id when constructing SDK state.
- Using a sample app, verify that sdk generates a random guid and saves it in local storage by comparing local storage value to running `mParticle.getDeviceId()` via developer console.
- Then add `deviceId: test-device-id` to the `config` object and verify that the config device id in dev console is the same the value that was added to the config.
- Closes …

fix: Revise priority of device id when initializing state

---

src/configAPIClient.ts
src/forwarders.js
test/src/tests-forwarders.js
test/src/utils.js

In order to support allowing multiple versions of our client side kits to be served, we add support for initializing kits based on suffix.  When a client side kit has 2 options (ex Braze v3 and v4), prior to this code, because the `kits` (previously `forwarders`) object is keyed by name, Braze v3 and Braze v4 have the same name (Appboy), and one kit would be replaced when the second Braze kit was added.  Now we suffix the kits so that in the above …

fix: Support suffix in kit initialization

---

.github/dependabot.yml

- Update Dependabot frequency to be weekly (on Sunday) instead of daily, so we can process updates on Monday before a release, if necessary.
- Update dependency types to limit to production only.
- N/A as this is a CI/CD update
- Closes https://go.mparticle.com/work/SQDSDKS-5756

ci: Revise dependabot to only weekly production updates

---

src/mp-instance.js

/developers/sdk/javascript was changed to /developers/sdk/web and this link update was missed in this file.
Note that http://docs.mparticle.com/developers/sdk/javascript/event-tracking#event-type does not work, but https://docs.mparticle.com/developers/sdk/web/event-tracking/#event-type does.
Tested link
- Closes https://go.mparticle.com/work/SQDSDKS-5865

docs: Update broken links in comments

---

src/forwarders.js
test/src/tests-forwarders.js

Filtered dictionaries were added after supporting side loaded kits.  However, after I added the filtered dictionaries support to the sideloaded kit class, I never included it when configuring the kits in the initialization flow, so all events were sent regardless of what filters were added.  This fixes that.
Added local tests, tested in a local app.
- Closes https://go.mparticle.com/work/SQDSDKS-5893

fix: Respect sideloaded kit filter dictionaries

---

test/cross-browser-testing/browserstack.karma.config.js
test/src/tests-core-sdk.js

To select browsers, I selected the version prior to what [this page](https://www.w3schools.com/js/js_versions.asp) says supports ES6 in order to ensure the browsers would fail with any es6 code.  
Safari and Edge were failing, so I incremented the versions until they passed, and then determined that those versions were still barely used and considered this to be sufficient.
Percentages were found by using these browsers have a combined ~.37% market share …

ci: Add legacy browsers for testing

---

.github/workflows/cross-browser-testing.yml
test/cross-browser-testing/browserstack.karma.config.js
test/src/tests-core-sdk.js

This PR sets up Browserstack tests in a Github Action. It follows the example workflow provided by the Browserstack docs here - https://www.browserstack.com/docs/automate/selenium/github-actions#sample-github-workflow-showing-a-browserstack-test
We originally discussed having it only be on release. However, I think it makes sense for it to be on push/pr also because we wouldn't want something to pass our non-CBT tests, merge them in, then upon release …

ci: Add Browserstack GIthub workflow

---

.github/workflows/cross-browser-testing.yml

The browserstack workflow does not have any build of the mparticle.js file. This means it will run new tests against a previous mparticle.js file, thus failing whenever new code is added to the core sdk.
Checked out a different branch and ran the build step in order to get tests to pass.
- Closes https://go.mparticle.com/work/SQDSDKS-6052

ci: Build mparticle.js before running CBT tests

---

src/apiClient.ts
src/constants.ts
src/mp-instance.js
src/store.ts
test/src/tests-core-sdk.js
test/src/tests-store.ts

Duplicating this PR - https://github.com/mParticle/mparticle-web-sdk/pull/797 which was already approved and merged into development, but undone due to blackout requirements.
This PR provides logic to incorporate the new `directURLRouting` feature flag.  The feature routes all external requests to the equivalent silo ie `jssdkcdn.us1.mparticle.com` as opposed to the default which is going through a generic fastly endpoint ie `jssdkcdn.mparticle.com`. …

feat: Support direct url routing from config (#797)

---

src/constants.ts
src/identity-utils.ts
src/identity.js
src/identityApiClient.js
src/mockBatchCreator.ts
src/mp-instance.js
src/mparticle-instance-manager.js
src/sdkRuntimeModels.ts
src/store.ts
src/validators.ts
test/jest/utils.ts
test/src/_test.index.ts
test/src/config/constants.ts
test/src/config/utils.js
test/src/tests-batchUploader.ts
test/src/tests-identities-attributes.js
test/src/tests-identity-utils.ts
test/src/tests-identity.js
test/src/tests-persistence.ts
test/src/tests-self-hosting-specific.js
test/src/tests-session-manager.ts
test/src/tests-store.ts

We want to cache our identity responses to limit superfluous identity calls.  This applies to login and identify for now.  In this PR, I leveraged the vault in order to create a new `idCache`.  
The keys for the idCache are a concatenation of the identities being passed to it along with the `das`.  An example value is as follows:
```
{
mpid: 'foo',
responseText: // cached response from the XHR request
expirationTimestamp: // number - the date being 1 day …
```

feat: Cache identity responses

---

src/identity-utils.ts
test/src/tests-identity-utils.ts

Hash the concatenated identities.
Unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6037

feat: Hash keys for idCache

---

src/identity-utils.ts
test/src/tests-identity-utils.ts

There were a few items on the xhr.responseText that we never use.  Rather than cache everything, just cache the items we need.
Updated unit tests
Tested on local sample app
- Closes https://go.mparticle.com/work/SQDSDKS-6103

fix: Prevent caching of UIs

---

src/identity-utils.ts
test/src/tests-identity-utils.ts

[Previous PR](https://github.com/mParticle/mparticle-web-sdk/pull/837) was approved but development was not up to date with latest release.  So I am adding the PR again and merging
- Closes https://go.mparticle.com/work/SQDSDKS-6103

fix: Only cache mpid and is_loggeed_in from xhr.responseText

---

src/apiClient.ts
src/audience.ts
src/audienceManager.ts
src/batchUploader.ts
src/constants.ts
src/identity.js
src/sdkRuntimeModels.ts
src/store.ts
src/uploaders.ts
test/jest/audience.spec.ts
test/src/_test.index.ts
test/src/tests-audience-manager.ts
test/src/tests-audience.ts
test/src/tests-store.ts

This PR provides for a new API on the current user: mParticle.Identity.getCurrentUser().getUserAudiences(callback).
The url it accesses is: https://jssdks.mparticle.com/v1/{apikey}/audiences?mpid=3984273492347328 and will return to the user the following schema to a callback:
```
{
currentAudiences: Audience[],
pastAudiences: Audience[]
}
```
- [] Was this tested locally? If not, explain why.
We are waiting for the backend to be updated before 
- Closes …

feat: Implement fetching user audiences

---

src/audience.ts
src/audienceManager.ts
src/uploaders.ts
test/jest/audience.spec.ts
test/src/tests-audience-manager.ts

Code has been updated to respect the following simplified backend response:
``` 
{
ct: 1710441407915,
dt: 'cam',  // current audience memberships
id: 'foo-id-2',
current_audience_memberships: [
{
audience_id: 9876,
expiration_timestamp_ms: 1234
},
{
audience_id: 5432,
expiration_timestamp_ms: null
},
]
};
```
The response to the user is an object that removes `ct`, `dt`, and `id` from the above, and only returns `current_audience_memberships`.
- Closes …

fix: Update audience logic to new backend response

---

src/audienceManager.ts
src/constants.ts
test/src/tests-audience-manager.ts

- This PR updates the url endpoint for audiences to be `nativesdks`, which expects `audience_memberships` and not `current_audience_memberships`
See screenshots for successful return of audiences 
- Closes https://go.mparticle.com/work/SQDSDKS-6278

fix: Update url to nativesdks and update server response

---

src/identity.interfaces.ts
src/identity.js
src/persistence.interfaces.ts
src/persistence.js
test/src/tests-identity.ts
test/src/tests-persistence.ts

- Move checkIdentitySwap function out of Identity
- Verify that identity swap behaves as expected
- Closes https://go.mparticle.com/work/SQDSDKS-6487

refactor: Move checkIdentitySwap out of Identity

---

src/sdkRuntimeModels.ts
test/src/tests-identities-attributes.ts

- Migrates Unit and Integration test for Identity Attributes from plain JavaScript to TypeScript.
- Run all build and automated tests to verify they pass correctly
- Using a sample app, manually verify that setting user attributes and other user identity functions behave as expected
- Closes https://go.mparticle.com/work/SQDSDKS-6463

Refactor: Migrate Identity Attribute Tests to TypeScript

---

src/store.ts
test/src/tests-self-hosting-specific.js

The Direct Url Routing flag currently is respected when customers load us via CDN, but I discovered a bug where it wasn't on self hosted environments.  This is because of how the config is treated and processed in CDN vs self hosted.
* CDN - All of the config and flags are in the same mparticle.js file that the server returns via CDN.  In this set up, the [flags are processed](https://github.com/mParticle/mparticle-web-sdk/blob/master/src/store.ts#L294), …

fix: Respect directUrlRouting flag in self hosted environments

---

src/ecommerce.js
src/events.js
test/src/tests-eCommerce.js

`logBaseEvent` allowed for `sourceMessageId` to be passed to it - [docs](https://docs.mparticle.com/integrations/facebook/event/#other-scenarios)
This is a feature so that facebook can de-dupe events based on an id.
However, this only works for custom events.  In the past, we added an options parameter to `logProductAction` (among other APIs), to allow for optional flags to be passed through.  We will leverage this open API to now let a key of …

feat: Enable passing sourceMessageId to logProductAction

---

src/ecommerce.js
test/src/config/utils.js
test/src/tests-event-logging.js
test/src/tests-integration-capture.ts

- Commerce events were having the custom flags for click ids supplanted completely by custom flags that were being passed from the user. This PR fixes that. Instead we `extend` the custom flags to include both the custom flags created by `createEventObject` as well as what is passed by the user, with the flags passed by the user taken as priority.
Added unit tests for ecommerce and page view, as well as an additional for custom events.
Manually tested …

fix: Support capturing click ids as custom flags in commerce events

---

README.md

- Current link to Web SDK docs results in a 404. This PR updates link to Web SDK documentation on docs.mparticle.com to point to the current web SDK reference
- Small fix, I just tested the URL to make sure it was correct.

docs: Update link to Web SDK docs in README.md

---

src/cookieSyncManager.interfaces.ts
src/cookieSyncManager.js
src/sdkRuntimeModels.ts

- Introduces type interfaces for Cookie Sync Manager
- N/A Does not change any actual functionality
- Closes https://go.mparticle.com/work/SQDSDKS-4800

refactor: Add Type interfaces for cookie sync manager

---

src/aliasRequestApiClient.ts
src/identityApiClient.interfaces.ts
test/src/tests-aliasRequestApiClient.ts

- Create Type Interfaces for Identity API Client
- N/A - Defines new type interfaces but they will not be used until we refactor api client
- Closes https://go.mparticle.com/work/SQDSDKS-6678

refactor: Add Type interfaces for identity api client

---

.gitignore
src/configAPIClient.ts
src/consent.ts
src/cookieSyncManager.interfaces.ts
src/cookieSyncManager.ts
src/mp-instance.js
src/persistence.interfaces.ts
src/sdkRuntimeModels.ts
src/store.ts
src/utils.ts
test/jest/cookieSyncManager.spec.ts
test/jest/utils.spec.ts
test/src/tests-cookie-syncing.ts

- Migrate CookieSyncManager to TypeScript and add Jest Unit Tests
- Run automated tests and verify that they continue to pass
- Closes https://go.mparticle.com/work/SQDSDKS-5084

refactor: Migrate CookieSyncManager to TypeScript

---

src/sdkRuntimeModels.ts
test/src/_test.index.ts
test/src/tests-mparticle-instance-manager.ts

- Migrates MP Instance Manager tests to TypeScript
- N/A - PR only updates tests. Run automated tests to verify.
- Closes https://go.mparticle.com/work/SQDSDKS-6771
- Must be merged after #950

refactor: Migrate Instance Manager Tests to TypeScript

---

src/integrationCapture.ts
test/jest/integration-capture.spec.ts
test/src/tests-integration-capture.ts

- Add support for Google Click Ids
- Run through automated tests. Manually configure sample app to use Integration Capture setting in backend and add relevant `gclid`, `gbraid`, `wbraid` values to query parameters.
- Closes https://go.mparticle.com/work/SQDSDKS-6947

feat: Add support for Google Click Ids

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

- Updates node versions used in PR and Release tasks to use more recent versions.
- N/A - this relates to ci/cd process
- Closes https://go.mparticle.com/work/SQDSDKS-6979

ci: Update Node versions for Automated tasks

---

src/constants.ts
src/identityApiClient.ts
test/src/config/utils.js
test/src/tests-core-sdk.js
test/src/tests-identityApiClient.ts

- Updates error handling and reporting for Identity API Client
- Adds more detailed messaging and better reflects actual Identity API Error Responses.
- Run SDK in sample app and disable networking. Manually modify identity requests with bad data and verify that errors are properly reported in developer console.
- Closes https://go.mparticle.com/work/SQDSDKS-6932

refactor: Update Error handling for Identity API Client

---

src/events.interfaces.ts
src/events.js
src/mp-instance.js
src/sdkRuntimeModels.ts

- Create Interface Definitions for Events
- N/A - This PR only defines new interfaces
- Closes https://go.mparticle.com/work/SQDSDKS-5593

refactor: Create Interfaces for Events

---

src/ecommerce.interfaces.ts
src/ecommerce.js
src/identity-user-interfaces.ts
src/sdkRuntimeModels.ts
src/sdkToEventsApiConverter.ts
src/serverModel.ts
test/src/tests-batchUploader_3.ts
test/src/tests-batchUploader_4.ts
test/src/tests-identities-attributes.ts
test/src/tests-identity.ts

- Defines TypeScript interfaces for eCommerce
- N/A - these are type definitions
- Closes https://go.mparticle.com/work/SQDSDKS-5678

refactor: Create Interfaces for eCommerce

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
.github/workflows/staging-step-1.yml

- V3 of `upload-artifact` and `download-artifact` [Github Actions are deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) and should be changed to v4.
- N/A - this is an update for our CI/CD process
- Closes https://go.mparticle.com/work/SQDSDKS-7030

ci: Update artifact Github Actions to v4

---

src/cookieSyncManager.ts
src/identity.js
src/utils.ts
test/jest/cookieSyncManager.spec.ts
test/jest/utils.spec.ts
test/src/tests-cookie-syncing.ts

This PR makes the cookie sync manager less cognitively complex by:
1. Not triggering cookie sync when `pixelUrl` is empty
2. Removing the logic between previousMPID and current mpid.  To simplify, we always test to see if the new mpid has a last sync date that has expired or not
3. Simplify `performCookieSync` by removing a lot of logic from it to `attemptCookieSync`
4. Reduce nested if statements throughout `attemptCookieSync`.
Unit tests continue to …

refactor: Simplify cookie sync manager

---

src/apiClient.ts
src/configAPIClient.ts
src/cookieSyncManager.ts
src/identityApiClient.ts
src/kitBlocking.ts
src/mockBatchCreator.ts
src/sdkToEventsApiConverter.ts
src/sessionManager.ts
test/jest/cookieSyncManager.spec.ts
test/src/config/setup.ts
test/src/tests-apiClient.ts
test/src/tests-audience-manager.ts
test/src/tests-batchUploader.ts
test/src/tests-batchUploader_2.ts
test/src/tests-batchUploader_3.ts
test/src/tests-batchUploader_4.ts
test/src/tests-beaconUpload.ts
test/src/tests-config-api-client.ts
test/src/tests-consent.ts
test/src/tests-cookie-syncing.ts
test/src/tests-feature-flags.ts
test/src/tests-identities-attributes.ts
test/src/tests-identity.ts
test/src/tests-identityApiClient.ts
test/src/tests-kit-blocking.ts
test/src/tests-legacy-alias-requests.ts
test/src/tests-mparticle-instance-manager.ts
test/src/tests-runtimeToBatchEventsDTO.ts
test/src/tests-session-manager.ts
test/src/tests-user.ts

- Revises imports of mP Instance interfaces

refactor: Migrate mParticle Instance Imports

---

src/vault.ts
test/src/vault.spec.ts

Allow the vault to save numbers properly.
Unit tests added
- Closes https://go.mparticle.com/work/SQDSDKS-7074

fix: Support numbers in vault

---

src/foregroundTimeTracker.ts
test/jest/foregroundTimeTracker.spec.ts

Updating the key from `mp-time` to `mprtcl-tos` to be consistent with other localstorage prefixes:
Updated unit tests and tested in a test app to get the above screenshot
- Closes https://go.mparticle.com/work/SQDSDKS-7105

fix: Update TOS local storage key

---

src/utils.ts
test/jest/utils.spec.ts

- Adds handlers to catch potentially malformed urls in `queryStringParser` fallback
- Set up sample app and pass in malformed strings into url as query parameter
- Closes https://go.mparticle.com/work/SQDSDKS-6989

fix: Add failsafes for queryStringParser

---

src/mp-instance.ts
src/mparticle-instance-manager.ts
src/sdkRuntimeModels.ts
test/src/tests-batchUploader_3.ts
test/src/tests-forwarders.ts
test/src/tests-integration-capture.ts
test/src/tests-kit-blocking.ts

- Migrates Forwarder Tests to TypeScript
- Verifies imported interfaces and types to ensure they are properly implemented.
- Verify automated tests pass and the repo builds properly
- Manually confirm Identity and Event Types are accessible via the `mParticle` object in the dev console.
- Closes https://go.mparticle.com/work/SQDSDKS-5767

refactor: Migrate Forwarder Tests to TypeScript

---

src/mp-instance.ts
src/mparticle-instance-manager.ts
src/roktManager.ts
src/sdkRuntimeModels.ts
test/jest/roktManager.spec.ts
test/src/tests-mparticle-instance-manager.ts

- Introduces a wrapper class for the Rokt SDK to allow integrations and partners to access Rokt functionality via the mParticle Web SDK.
- Using a sample app, attempt to access the `window.mParticle.Rokt.selectPlacements()` method.
- Add the [Rokt Web SDK](https://docs.rokt.com/developers/integration-guides/web/best-practices/) to your sample app and attempt to attach the launcher through `window.mParticle.Rokt.attachLauncher()`.
- `selectPlacement` …

feat: Add Rokt Wrapper

---

src/forwarders.interfaces.ts
src/sdkRuntimeModels.ts
src/store.ts
test/jest/sideloadedKit.spec.ts
test/jest/utils.ts

- Defines specific interfaces for Kits:
- UnregisteredKit - The state of a kit when imported via a kit config via NPM/CDN
- RegisteredKit - A kit that has a constructor and is assigned to the forwarderConstructors data structure and can be configured
- ConfiguredKit - the "final" state of a kit where it can be acted upon by the SDK
- N/A - this just changes kit interfaces within the SDK
- Closes https://go.mparticle.com/work/SQDSDKS-6035

refactor: Create Distinct Kit Interfaces

---

src/batchUploader.ts
test/src/tests-batchUploader.ts

Because the AST background event is added as the last event in the batch, and the batch converter takes values from the last event to append to the batch, we need to ensure the AST background event has ALL of the keys that the batch needs to prevent any batch that includes this AST from having a blank key that should be populated.
Added unit tests and did local testing to confirm all values come abck
- Closes https://go.mparticle.com/work/SQDSDKS-7145

fix: Add app name, version, package to AST background event

---

src/roktManager.ts
test/jest/roktManager.spec.ts

- Refactors the queueMessage logic of the Rokt Manager to defer promises for Rokt functions so that consumers can properly await the results.
- Using a sample web app, make a call to `selectPlacements` that triggers before the mParticle web sdk finishes loading the Rokt Web Kit. The call should return placements correctly after queuing.
As an example:
```javascript
mParticle.ready( async function () {
try {
const selection = await …
```

fix: Refactor RoktManager with deferred call handling and message queue processing
