mParticle/mparticle-web-sdk

mparticle.js
Gives you an option to send events via XHR request via the JS SDK instead of using the native SDK when the App is embedded in a web view.
=> Add useNativeSdk option to config

src/main.js, test/src/tests-event-logging.js
This change allows custom attributes to be passed to the logError function.
Tests have been added to verify that custom attributes are included on the custom event logged, and that the values are sanitized.
=> Feature: log error custom attributes

src/mp-instance.js, test/src/tests-core-sdk.js
Add a warning for v2 Users to notify them of an upcoming upgrade
N/A
Closes https://go.mparticle.com/work/SQDSDKS-3722
=> fix: add warning of upcoming upgrade for V2 Users

package-lock.json, package.json
Remove YUI from package.json
N/A
Closes https://go.mparticle.com/work/SQDSDKS-4179
=> fix: Remove YUI from package.json

package-lock.json
=> fix: Rebuild package-lock.json

.github/workflows/release.yml
- Add Build and Test job to release action so that integration, linting and other tests can occur before release jobs.
Closes https://go.mparticle.com/work/SQDSDKS-4231
=> ci: Update release to include integration tests

.github/workflows/calculate-difference.yml
Create Reusable Github Action to calculate difference as a percent between two numbers
Closes https://go.mparticle.com/work/SQDSDKS-4352
=> ci: Create action to calculate percent difference

src/forwarders.js, test/src/tests-forwarders.js, test/src/utils.js
Add logger to kits so that kits can log to the custom mp logger
Unit tests, local test app
Closes https://go.mparticle.com/work/SQDSDKS-4464
=> feat: Add custom logger to kits

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml, .github/workflows/dependabot-branch-rebase.yml
- Automate Dependabot Automerge
Closes https://go.mparticle.com/work/SQDSDKS-4487
=> ci: Update Dependabot Automerge

package-lock.json, package.json
Manually merging in several dependabot bumps
=> chore: Merge Dependabot

rollup.test.config.js, src/helpers.js, src/sdkRuntimeModels.ts, src/store.js, src/store.ts, src/utils.ts, src/validators.ts, test/src/tests-batchUploader.ts, test/src/tests-core-sdk.js, test/src/tests-event-logging.js, test/src/tests-main.js, test/src/tests-store.ts, test/src/tests-utils.ts, tsconfig.json
- Migrate Store Module to TypeScript
- Manually test in a sample app to verify store builds correctly
Closes https://go.mparticle.com/work/SQDSDKS-4328
=> refactor: Migrate Store to TypeScript

.github/workflows/android-bridge-tests.yml, .github/workflows/calculate-difference.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, package-lock.json, package.json
- Remove references to Node 12 in Github Actions
- Fix Firefox Runner
- Run Github Actions
Closes https://go.mparticle.com/work/SQDSDKS-4873
=> fix: Fix Firefox Runner and Remove references to node 12

src/vault.ts, test/src/tests-main.js, test/src/tests-vault.ts
- Create a Wrapper Class around Local Storage
- Wrapper should allow batches to be saved and retrieved from local storage
- Wrapper should allow batches to be purged without affecting other local storage items
- This wrapper will be part of a larger initiative to refactor persistence
- N/A
Closes https://go.mparticle.com/work/SQDSDKS-4714
=> feat: Add Persistence Wrapper

.github/workflows/pull-request.yml
- Add semgrep on pull request runs
- Ran semgrep locally, no findings available. Letting this test run do all the talking
=> ci: Add semgrep static analysis

src/consent.interfaces.ts, src/mockBatchCreator.ts, src/sdkRuntimeModels.ts, src/sdkToEventsApiConverter.ts, src/serverModel.ts, src/store.ts, test/src/tests-consent.ts, test/src/tests-serverModel.ts
- Migrate Consent Tests to TypeScript
- Fix or report any inconsistent Types that are affected
- Closes https://go.mparticle.com/work/SQDSDKS-5004
[SQDSDKS-5004]: https://mparticle-eng.atlassian.net/browse/SQDSDKS-5004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Migrate Consent Tests to TypeScript

src/apiClient.ts, src/mockBatchCreator.ts, src/sdkRuntimeModels.ts, test/src/config.ts, test/src/tests-apiClient.ts
- Migrate API Client Module and Tests to TypeScript
- Closes https://go.mparticle.com/work/SQDSDKS-5005
=> refactor: Migrate API Client to TypeScript

.github/workflows/release.yml
- Currently our release process is running tests on the main branch, but it should be using development to run tests
- Because it is an issue with the release process
- Closes https://go.mparticle.com/work/SQDSDKS-5029
=> ci: Revise release job to run development tests

src/cookieSyncManager.js
- Document and highlight refactor points for Cookie Sync
- Unnecessary as this is just adding comments to the code.
- Closes https://go.mparticle.com/work/SQDSDKS-5086
=> docs: Add Comments for Cookie Sync Module

src/vault.ts, test/src/tests-vault.ts
- Simplify Vault Implementation to be used as a simple local storage wrapper with a simplified API.
- Closes https://go.mparticle.com/work/SQDSDKS-5146
=> refactor: Simplify Vault for Offline Storage

src/batchUploader.ts, test/src/tests-batchUploader.ts, test/src/tests-beaconUpload.ts, test/src/tests-main.js
- Events and Batches should be created and uploaded in the order they were created.
- Write regression tests to verify this logic does not change drastically in any future code commits
- Fix upload logic to interrupt transmission reattempts in case of any network interruption.
- Closes https://go.mparticle.com/work/SQDSDKS-5104
=> fix: Verify Batches and events are uploaded in order of creation

src/persistence.interfaces.ts, src/persistence.js, src/sdkRuntimeModels.ts, src/store.ts
- Define type definitions for Persistence Module
- Tested via local typescript test module
- Closes https://go.mparticle.com/work/SQDSDKS-5168
=> refactor: Define Type Definitions for Persistence

.github/dependabot.yml
- {provide a thorough description of the changes}
=> ci: Update Dependabot Target Branch

.github/workflows/pull-request.yml
Update automerge dependabot job
- Closes https://go.mparticle.com/work/SQDSDKS-5204
=> ci: Update dependabot automerge job

.github/workflows/pull-request.yml, src/constants.ts
- Display a Git Diff of our bundled mparticle.js so we can spot check during code review
- N/A - This is a Github Action change
- Closes https://go.mparticle.com/work/SQDSDKS-5225
=> ci: Add Git Diff to PR Actions

src/persistence.interfaces.ts, src/persistence.js, src/sdkRuntimeModels.ts, test/src/config.ts, test/src/tests-persistence.ts
- Migrate Persistence Tests to Typescript as part of a phased approach of migrating Persistence to TypeScript
- N/A as this is only changing automated tests
- Closes https://go.mparticle.com/work/SQDSDKS-5169
=> refactor: Update Persistence Tests to TypeScript

test/src/tests-batchUploader.ts, test/src/tests-beaconUpload.ts, test/src/tests-cookie-syncing.js, test/src/tests-core-sdk.js, test/src/tests-eCommerce.js, test/src/tests-event-logging.js, test/src/tests-forwarders.js, test/src/tests-helpers.js, test/src/tests-identities-attributes.js, test/src/tests-identity.js, test/src/tests-mParticleUser.js, test/src/tests-mparticle-instance-manager.js, test/src/tests-native-sdk.js, test/src/tests-queue-public-methods.js, test/src/tests-self-hosting-specific.js, test/src/tests-serverModel.ts, test/src/tests-store.ts, test/src/tests-temp-session-bug-fix.js, test/src/tests-validators.ts
`var` --> `const`/`let`
- Closes https://go.mparticle.com/work/SQDSDKS-5356
=> test: Replace all instances of var in tests folder to const/let

.github/workflows/pull-request.yml, .github/workflows/release.yml
- Replaces Test Runners with Reusable Workflows
- Mirrors PR and Release Test Strategy
- N/A - this is an update to our CI/CD process
- Closes https://go.mparticle.com/work/SQDSDKS-5164
=> ci: Revise Release GHA to run tests in parallel

.github/workflows/release.yml
- Remove duplicate test steps from build task, as they are already defined in their own jobs
- N/A - Changes only apply to ci/cd
- Closes https://go.mparticle.com/work/SQDSDKS-5417
=> ci: Remove unnecessary tests from release.yml

.github/workflows/release.yml
- Rename and remove integration tests from Build Job in release.yml
- N/A - Changes only apply to ci/cd
- Closes https://go.mparticle.com/work/SQDSDKS-5418
=> ci: Rename and refactor build task in release.yml

jest.config.js, package-lock.json, package.json, src/forwarders.js, src/mockBatchCreator.ts, src/mparticle-instance-manager.js, src/sdkRuntimeModels.ts, src/sideloadedKit.ts, test/jest/sideloadedKit.spec.ts, test/jest/utils.ts, test/src/tests-forwarders.js, test/src/utils.js
This PR exposes the MPSideloadedKit class to the public API and refactors code to consider the changes necessary for the new class - primarily replacing `sideloadedKit.register` with `sideloadedKit.kitInstance.register`
- Closes https://go.mparticle.com/work/SQDSDKS-5351
=> feat: Expose MPSideloadedKit class to public API

test/src/tests-batchUploader.ts
- Noticed that an asynchronous test was firing an event but was not actually caught by the `done()` function, and it was colliding with a subsequent test.
- N/A - Just changing tests
- Closes https://go.mparticle.com/work/SQDSDKS-5383
=> test: Fix Flakey Offline Storage Tests

package-lock.json, package.json
- Merge in latest Dependabot package updates
- Run Automated Tests
- Test using local sample app
- Closes https://go.mparticle.com/work/SQDSDKS-5467
=> chore: Merge Dependabot Updates

package-lock.json, package.json
- Manually merge in Dependabot updates
- Run automated tests and manually test with sample app
- Closes https://go.mparticle.com/work/SQDSDKS-5518
=> chore: Manually merge dependabot

package-lock.json
- Merging Dependabot updates
- Run automated tests and manually smoke test using a sample app
- Closes https://go.mparticle.com/work/SQDSDKS-5554
=> chore: Manually Merge Dependabot Updates

package-lock.json
- Manually merge in dependabot updates
- Closes https://go.mparticle.com/work/SQDSDKS-5884
=> ci: Manually Merge Dependabot

test/src/tests-batchUploader.ts
Our batchuploader tests used setTimeout which caused some flakiness.  This PR replaces these with an async/await test structure.
- Closes https://go.mparticle.com/work/SQDSDKS-5998
=> test: Refactor batchUploader tests

README.md
We need to include `This project is tested with BrowserStack` to keep Browserstack free for us.
- Closes https://go.mparticle.com/work/SQDSDKS-6030
=> docs: Update readme to include Browserstack testing

src/constants.ts, src/identity-utils.ts, src/identity.js, src/identityApiClient.js, src/mockBatchCreator.ts, src/mp-instance.js, src/mparticle-instance-manager.js, src/sdkRuntimeModels.ts, src/store.ts, src/validators.ts, test/jest/utils.ts, test/src/_test.index.ts, test/src/config/constants.ts, test/src/config/utils.js, test/src/tests-batchUploader.ts, test/src/tests-identities-attributes.js, test/src/tests-identity-utils.ts, test/src/tests-identity.js, test/src/tests-persistence.ts, test/src/tests-self-hosting-specific.js, test/src/tests-session-manager.ts, test/src/tests-store.ts
This PR is a feature branch which composes of the following previously approved PRs:
* https://github.com/mParticle/mparticle-web-sdk/pull/819
* https://github.com/mParticle/mparticle-web-sdk/pull/833
It implements Identity Caching to prevent superfluous identity calls.  Applies only to identify/login right now.  Modify and logout will clear the cache.  Each cache lasts for 24 hours before being removed.
- {explain how this has been tested, and what, if …
=> feat: Implement identity caching

src/constants.ts, src/identity.js, src/store.ts, test/src/tests-identity.js, test/src/tests-store.ts
- This PR implements a feature flag for audience API to work
- Closes https://go.mparticle.com/work/SQDSDKS-6318
=> fix: Implement audience API feature flag

test/src/tests-event-logging.js, test/src/tests-forwarders.js, test/src/tests-identity.js
- During a recent refactor, #864 we introduced a bug with how we process `modify` requests, which revealed a gap in our test coverage. We have update some of our older tests to properly mock `modify` requests.
- The draft commit #880 highlights these updated tests within the context of the bug to show how tests failing when the bug is introduced.
- Closes https://go.mparticle.com/work/SQDSDKS-6403
=> test: Add Test Coverage for Modify and Identity Requests

src/apiClient.ts, src/batchUploader.ts, src/consent.ts, src/forwarders.interfaces.ts, src/identity-user-interfaces.ts, src/identity-utils.ts, src/identity.interfaces.ts, src/identity.js, src/persistence.interfaces.ts, src/sdkRuntimeModels.ts, src/sdkToEventsApiConverter.ts, src/serverModel.ts, src/sessionManager.ts, src/utils.ts, src/validators.ts, test/jest/identity.spec.ts, test/src/tests-apiClient.ts, test/src/tests-persistence.ts, test/src/tests-runtimeToBatchEventsDTO.ts, test/src/tests-serverModel.ts
- Defines TypeScript interfaces for Identity Module and User Object
- Replaces usages from `sdkRuntimeModels` with new usages
- Use Jest Tests to identify which interfaces are properly defined.
- Closes https://go.mparticle.com/work/SQDSDKS-6418
=> refactor: Create Identity and User Interfaces for TypeScript

src/identity-user-interfaces.ts, src/identity-utils.ts, src/identity.interfaces.ts, src/sdkRuntimeModels.ts, src/store.ts, src/type-utils.ts, src/types.interfaces.ts, test/jest/identity.spec.ts, test/src/tests-identity.ts
- Migrates Unit and Integration test for Identity from plain JavaScript to TypeScript, along with new interfaces.
- Run all build and automated tests to verify they pass correctly
- Using a sample app, manually verify that identify, login, logout, and modify requests behave as expected
- Closes https://go.mparticle.com/work/SQDSDKS-6419
=> refactor: Migrate Identity Tests to TypeScript

src/identity.js, src/identityApiClient.js, src/persistence.js, src/sdkRuntimeModels.ts, src/serverModel.ts
- Identify future refactor points for Identity related workflows
- N/A - this only adds comments to certain parts of the code
- Closes https://go.mparticle.com/work/SQDSDKS-6486
=> refactor: Identify refactor points in Identity related workflows

src/identity.interfaces.ts, src/identity.js, src/store.ts, src/type-utils.ts, src/types.js, src/user-utils.ts, src/utils.ts, test/jest/type-utils.spec.ts, test/jest/user-utils.spec.ts, test/src/tests-store.ts, test/src/tests-utils.ts
- Reintroduces #864 after a revert #879, with more test coverage.
- Using a sample app, verify that all identity methods work as expected
- Closes https://go.mparticle.com/work/SQDSDKS-6461
=> refactor: Refactor ParseIdentityResponse Workflow

src/configAPIClient.ts
- {provide a thorough description of the changes}
=> Clean up configAPIClient and make it readable

rollup.config.js, src/mparticle-instance-manager.ts, src/sdkRuntimeModels.ts, test/jest/sideloadedKit.spec.ts, test/src/tests-batchUploader_2.ts, test/src/tests-batchUploader_3.ts, test/src/tests-batchUploader_4.ts, test/src/tests-beaconUpload.ts, test/src/tests-config-api-client.ts, test/src/tests-consent.ts, test/src/tests-cookie-syncing.ts, test/src/tests-feature-flags.ts, test/src/tests-identities-attributes.ts, test/src/tests-identity.ts, test/src/tests-identityApiClient.ts, test/src/tests-kit-blocking.ts, test/src/tests-legacy-alias-requests.ts, test/src/tests-mparticle-instance-manager.ts, test/src/tests-runtimeToBatchEventsDTO.ts, test/src/tests-session-manager.ts, test/src/tests-user.ts
- {provide a thorough description of the changes}
=> refactor: Migrate mParticle Instance Manager to TypeScript

src/integrationCapture.ts, src/serverModel.ts, test/jest/integration-capture.spec.ts, test/src/tests-integration-capture.ts
- Adds Rokt Click Id to Integration Capture as a Custom Flag
- https://docs.rokt.com/developers/integration-guides/web/advanced/rokt-id-tag/#test-the-rokt-id
- Use a sample app to verify capture of Rokt Click Id via url parameter
- Closes https://go.mparticle.com/work/SQDSDKS-7078
=> fix: Add Rokt Click ID for Integration Capture

src/integrationCapture.ts, test/jest/integration-capture.spec.ts, test/src/tests-integration-capture.ts
- Adds SnapChat ClickID to custom_flags to events.
- [ ✔️ ] Yes tested locally. 
- All local tests passed. 
-  
=> feat: adds native collection of snap click ID

test/karma.config.js, test/src/config/utils.js, test/src/tests-batchUploader_3.ts, test/src/tests-cookie-syncing.ts, test/src/tests-core-sdk.js, test/src/tests-forwarders.ts, test/src/tests-helpers.js, test/src/tests-identity.ts, test/src/tests-kit-blocking.ts, test/src/tests-mparticle-instance-manager.ts, test/src/tests-self-hosting-specific.js
This PR pulls 2 commits [from here](https://github.com/mParticle/mparticle-web-sdk/pull/967/commits), and then also updates the identity tests to use async/await - this file seemed to be the cause of some other tests breaking.  
Unit tests run successfullyl
- Closes https://go.mparticle.com/work/SQDSDKS-7143
=> test: Remove set timeouts from tests and other cleanup

src/batchUploader.ts
Remove console.log
Local test app
=> fix: Remove console.log

src/integrationCapture.ts, test/jest/integration-capture.spec.ts, test/src/tests-integration-capture.ts
- Adds support for a new format of Click ID from Rokt (`rclid`)
- Run automated tests and use a sample app by passing `rclid` in the query parameters.
- Closes https://go.mparticle.com/work/SQDSDKS-7146
=> fix: Update Rokt Click ID

src/batchUploader.ts, test/src/tests-batchUploader.ts
Update BatchUploader to include integration attributes and cust…om flags in AST events
- {provide a thorough description of the changes}
=> fix: Update BatchUploader to include integration attributes on AST Background Events

test/src/tests-forwarders.ts
- Updated all occurrences of .then to async/await within tests-forwarders
- Closes https://rokt.atlassian.net/browse/SDKE-345
=> test: converted .then to async/await in tests-forwarders

test/integrations/requirejs/test-requirejs.js
- Updated all occurrences of .then to async/await within `requirejs`.
- Closes https://rokt.atlassian.net/browse/SDKE-355
=> test: convert then to async/await in requirejs
